#! /usr/bin/env bash
echo '******* Starting on_containerize'
source /usr/bin/tools
if [ dev_mode ]; then
  # so, if were in dev mode we apparently need to do some cleanup 
  # for our build pack to run.  This may need to be done elsewhere, but since
  # I'm not convinced it's cool to run all the time, we'll do it conditionally
  # based on dev_mode
  if [ -z "${APP_IN}" ] ; then
    error "no value for APP_IN something is not going to work"
  else
    set -x
    rm -rf ${APP_IN}/.heroku
    set +x
  fi
fi
echo '******* Ending on_containerize'

